/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllTimeStats {
  'wins' : bigint,
  'bestStreakEver' : bigint,
  'losses' : bigint,
  'totalGames' : bigint,
}
export interface Availability { 'time' : string, 'notes' : [] | [string] }
export type BadgeCriteria = { 'consecutiveWeeksAvailable' : bigint } |
  { 'firstMatchLogged' : bigint } |
  { 'totalGamesPlayed' : bigint } |
  { 'daysAtNumber1' : bigint } |
  { 'totalWins' : bigint } |
  { 'winsStreak' : bigint } |
  { 'totalChatMessages' : bigint } |
  { 'totalGames' : bigint } |
  { 'topLeaderboardPosition' : bigint } |
  { 'winPercentage' : bigint } |
  { 'monthlyParticipation' : MonthCriteria } |
  { 'firstImageUploaded' : bigint } |
  { 'totalDaysAvailable' : bigint } |
  { 'totalLikesReceived' : bigint } |
  { 'bestWinStreak' : bigint };
export interface BadgeDefinition {
  'id' : string,
  'name' : string,
  'description' : string,
  'criteria' : BadgeCriteria,
}
export interface DayAvailabilityCount { 'day' : bigint, 'count' : bigint }
export interface DayWithLog {
  'day' : bigint,
  'wins' : bigint,
  'losses' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface MonthCriteria {
  'month' : bigint,
  'matchesThreshold' : bigint,
  'year' : bigint,
}
export interface Notification {
  'id' : bigint,
  'oldRank' : [] | [bigint],
  'read' : boolean,
  'recipient' : Principal,
  'badgeId' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
  'category' : NotificationCategory,
  'relatedPostId' : [] | [bigint],
  'newRank' : [] | [bigint],
}
export type NotificationCategory = { 'availabilityOverlap' : null } |
  { 'rankChange' : null } |
  { 'badgeUnlock' : null } |
  { 'mention' : null } |
  { 'reply' : null };
export interface Post {
  'id' : bigint,
  'content' : string,
  'edited' : boolean,
  'author' : Principal,
  'editTimestamp' : [] | [bigint],
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
  'parentId' : [] | [bigint],
  'likesCount' : bigint,
  'dislikesCount' : bigint,
}
export interface PostWithReplies {
  'post' : Post,
  'replies' : Array<PostWithReplies>,
}
export type ReactionType = { 'like' : null } |
  { 'dislike' : null };
export interface SeasonSnapshot {
  'leaderboard' : Array<[Principal, T]>,
  'year' : bigint,
}
export interface T {
  'streak' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'totalGames' : bigint,
  'bestStreak' : bigint,
}
export interface UserProfile {
  'name' : string,
  'customProfilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAvailability' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'addPost' : ActorMethod<[string, [] | [bigint], [] | [ExternalBlob]], bigint>,
  'addReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'anyUserHasAvailability' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadgeToUser' : ActorMethod<[Principal, string], undefined>,
  'createBadgeDefinition' : ActorMethod<[BadgeDefinition], undefined>,
  'daysWithAnyAvailability' : ActorMethod<[Array<bigint>], Array<boolean>>,
  'decrementDailyLog' : ActorMethod<[bigint, boolean], undefined>,
  'deleteAllDayAvailabilities' : ActorMethod<[bigint], undefined>,
  'deleteBadgeDefinition' : ActorMethod<[string], undefined>,
  'deleteCallerDayAvailability' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'deleteUserDayAvailability' : ActorMethod<[Principal, bigint], undefined>,
  'editPost' : ActorMethod<[bigint, string], undefined>,
  'finalizeCurrentSeason' : ActorMethod<[bigint], undefined>,
  'getAllAvailabilities' : ActorMethod<[], Array<[Principal, bigint, string]>>,
  'getAllBadgeDefinitions' : ActorMethod<[], Array<BadgeDefinition>>,
  'getAllDayAvailabilityCounts' : ActorMethod<[], Array<DayAvailabilityCount>>,
  'getAllLoginTimestamps' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAllRegisteredUsers' : ActorMethod<
    [],
    Array<[Principal, UserProfile, bigint]>
  >,
  'getAllTimeLeaderboard' : ActorMethod<[], Array<[Principal, AllTimeStats]>>,
  'getCallerAvailability' : ActorMethod<[bigint], [] | [Availability]>,
  'getCallerAvailableDaysWithLogs' : ActorMethod<[], Array<DayWithLog>>,
  'getCallerStats' : ActorMethod<[], [] | [T]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentSeasonLeaderboard' : ActorMethod<[], Array<[Principal, T]>>,
  'getDayAvailability' : ActorMethod<
    [bigint],
    Array<[Principal, Availability]>
  >,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, T]>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyRankHistory' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getPastSeasonSnapshots' : ActorMethod<[], Array<SeasonSnapshot>>,
  'getPostWithReplies' : ActorMethod<[bigint], [] | [PostWithReplies]>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getRankHistory' : ActorMethod<[Principal], Array<[bigint, bigint]>>,
  'getReplies' : ActorMethod<[bigint], Array<Post>>,
  'getScoreLeaderboardWithStats' : ActorMethod<
    [],
    Array<[Principal, T, bigint]>
  >,
  'getTopPlayersByScore' : ActorMethod<[bigint], Array<[Principal, T]>>,
  'getTotalPostCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserBadges' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], [] | [T]>,
  'hasAvailability' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'recordDailyLoss' : ActorMethod<[bigint], undefined>,
  'recordDailyWin' : ActorMethod<[bigint], undefined>,
  'recordLoginTime' : ActorMethod<[], undefined>,
  'removeReaction' : ActorMethod<[bigint], undefined>,
  'revokeBadgeFromUser' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBadgeDefinition' : ActorMethod<[BadgeDefinition], undefined>,
  'updateCallerStats' : ActorMethod<[T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];