/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Availability = IDL.Record({
  'time' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const T = IDL.Record({
  'streak' : IDL.Int,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAvailability' : IDL.Func([IDL.Int, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllLoginTimestamps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'getCallerAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(Availability)],
      ['query'],
    ),
  'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getRecentMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getTopPlayersByWinPercentage' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
  'getWinPercentageLeaderboardWithStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
      ['query'],
    ),
  'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLoginTime' : IDL.Func([], [], []),
  'recordLoss' : IDL.Func([], [], []),
  'recordWin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'updateCallerStats' : IDL.Func([T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Availability = IDL.Record({
    'time' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const T = IDL.Record({
    'streak' : IDL.Int,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAvailability' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllLoginTimestamps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'getCallerAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(Availability)],
        ['query'],
      ),
    'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getRecentMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getTopPlayersByWinPercentage' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
    'getWinPercentageLeaderboardWithStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
        ['query'],
      ),
    'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLoginTime' : IDL.Func([], [], []),
    'recordLoss' : IDL.Func([], [], []),
    'recordWin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'updateCallerStats' : IDL.Func([T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };