/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'customProfilePicture' : IDL.Opt(ExternalBlob),
});
export const Availability = IDL.Record({
  'time' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const T = IDL.Record({
  'streak' : IDL.Int,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalGames' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAvailability' : IDL.Func([IDL.Int, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
  'deleteCallerDayAvailability' : IDL.Func([IDL.Int], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'deleteUserDayAvailability' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'getAllAvailabilities' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int, IDL.Text))],
      ['query'],
    ),
  'getAllLoginTimestamps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'getAllRegisteredUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile, IDL.Int))],
      ['query'],
    ),
  'getCallerAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(Availability)],
      ['query'],
    ),
  'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getRecentMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getTopPlayersByWinPercentage' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
  'getWinPercentageLeaderboardWithStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
      ['query'],
    ),
  'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLoginTime' : IDL.Func([], [], []),
  'recordLoss' : IDL.Func([], [], []),
  'recordWin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'updateCallerStats' : IDL.Func([T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'customProfilePicture' : IDL.Opt(ExternalBlob),
  });
  const Availability = IDL.Record({
    'time' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const T = IDL.Record({
    'streak' : IDL.Int,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAvailability' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
    'deleteCallerDayAvailability' : IDL.Func([IDL.Int], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'deleteUserDayAvailability' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'getAllAvailabilities' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int, IDL.Text))],
        ['query'],
      ),
    'getAllLoginTimestamps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'getAllRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile, IDL.Int))],
        ['query'],
      ),
    'getCallerAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(Availability)],
        ['query'],
      ),
    'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getRecentMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getTopPlayersByWinPercentage' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
    'getWinPercentageLeaderboardWithStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
        ['query'],
      ),
    'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLoginTime' : IDL.Func([], [], []),
    'recordLoss' : IDL.Func([], [], []),
    'recordWin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'updateCallerStats' : IDL.Func([T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };