/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Availability { 'time' : string, 'notes' : [] | [string] }
export interface T {
  'streak' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'totalGames' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAvailability' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllDayAvailabilities' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllLoginTimestamps' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getCallerAvailability' : ActorMethod<[bigint], [] | [Availability]>,
  'getCallerStats' : ActorMethod<[], [] | [T]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDayAvailability' : ActorMethod<
    [bigint],
    Array<[Principal, Availability]>
  >,
  'getLeaderboard' : ActorMethod<[string], Array<[Principal, T]>>,
  'getRecentMessages' : ActorMethod<
    [bigint],
    Array<[Principal, string, bigint]>
  >,
  'getTopPlayersByWinPercentage' : ActorMethod<[bigint], Array<[Principal, T]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], [] | [T]>,
  'getWinPercentageLeaderboardWithStats' : ActorMethod<
    [],
    Array<[Principal, T, bigint]>
  >,
  'hasAvailability' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordLoginTime' : ActorMethod<[], undefined>,
  'recordLoss' : ActorMethod<[], undefined>,
  'recordWin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'updateCallerStats' : ActorMethod<[T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];