/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostWithReplies = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ReactionType = IDL.Variant({
  'like' : IDL.Null,
  'dislike' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BadgeCriteria = IDL.Variant({
  'totalWins' : IDL.Nat,
  'winsStreak' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const BadgeDefinition = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'criteria' : BadgeCriteria,
});
export const DayAvailabilityCount = IDL.Record({
  'day' : IDL.Int,
  'count' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'customProfilePicture' : IDL.Opt(ExternalBlob),
});
export const Availability = IDL.Record({
  'time' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const DayWithLog = IDL.Record({
  'day' : IDL.Int,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
});
export const T = IDL.Record({
  'streak' : IDL.Int,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalGames' : IDL.Nat,
  'bestStreak' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Int,
  'content' : IDL.Text,
  'edited' : IDL.Bool,
  'author' : IDL.Principal,
  'editTimestamp' : IDL.Opt(IDL.Int),
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
  'parentId' : IDL.Opt(IDL.Int),
  'likesCount' : IDL.Nat,
  'dislikesCount' : IDL.Nat,
});
PostWithReplies.fill(
  IDL.Record({ 'post' : Post, 'replies' : IDL.Vec(PostWithReplies) })
);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAvailability' : IDL.Func([IDL.Int, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addPost' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(ExternalBlob)],
      [IDL.Int],
      [],
    ),
  'addReaction' : IDL.Func([IDL.Int, ReactionType], [], []),
  'anyUserHasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBadgeDefinition' : IDL.Func([BadgeDefinition], [], []),
  'daysWithAnyAvailability' : IDL.Func(
      [IDL.Vec(IDL.Int)],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  'decrementDailyLog' : IDL.Func([IDL.Int, IDL.Bool], [], []),
  'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
  'deleteBadgeDefinition' : IDL.Func([IDL.Text], [], []),
  'deleteCallerDayAvailability' : IDL.Func([IDL.Int], [], []),
  'deletePost' : IDL.Func([IDL.Int], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'deleteUserDayAvailability' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'editPost' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'getAllAvailabilities' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int, IDL.Text))],
      ['query'],
    ),
  'getAllBadgeDefinitions' : IDL.Func(
      [],
      [IDL.Vec(BadgeDefinition)],
      ['query'],
    ),
  'getAllDayAvailabilityCounts' : IDL.Func(
      [],
      [IDL.Vec(DayAvailabilityCount)],
      ['query'],
    ),
  'getAllLoginTimestamps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'getAllRegisteredUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile, IDL.Int))],
      ['query'],
    ),
  'getCallerAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(Availability)],
      ['query'],
    ),
  'getCallerAvailableDaysWithLogs' : IDL.Func(
      [],
      [IDL.Vec(DayWithLog)],
      ['query'],
    ),
  'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayAvailability' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getPostWithReplies' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(PostWithReplies)],
      ['query'],
    ),
  'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getReplies' : IDL.Func([IDL.Int], [IDL.Vec(Post)], ['query']),
  'getScoreLeaderboardWithStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
      ['query'],
    ),
  'getTopPlayersByScore' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
      ['query'],
    ),
  'getUserBadges' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
  'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordDailyLoss' : IDL.Func([IDL.Int], [], []),
  'recordDailyWin' : IDL.Func([IDL.Int], [], []),
  'recordLoginTime' : IDL.Func([], [], []),
  'removeReaction' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBadgeDefinition' : IDL.Func([BadgeDefinition], [], []),
  'updateCallerStats' : IDL.Func([T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostWithReplies = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ReactionType = IDL.Variant({ 'like' : IDL.Null, 'dislike' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BadgeCriteria = IDL.Variant({
    'totalWins' : IDL.Nat,
    'winsStreak' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const BadgeDefinition = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'criteria' : BadgeCriteria,
  });
  const DayAvailabilityCount = IDL.Record({
    'day' : IDL.Int,
    'count' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'customProfilePicture' : IDL.Opt(ExternalBlob),
  });
  const Availability = IDL.Record({
    'time' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const DayWithLog = IDL.Record({
    'day' : IDL.Int,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
  });
  const T = IDL.Record({
    'streak' : IDL.Int,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalGames' : IDL.Nat,
    'bestStreak' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Int,
    'content' : IDL.Text,
    'edited' : IDL.Bool,
    'author' : IDL.Principal,
    'editTimestamp' : IDL.Opt(IDL.Int),
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
    'parentId' : IDL.Opt(IDL.Int),
    'likesCount' : IDL.Nat,
    'dislikesCount' : IDL.Nat,
  });
  PostWithReplies.fill(
    IDL.Record({ 'post' : Post, 'replies' : IDL.Vec(PostWithReplies) })
  );
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAvailability' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addPost' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(ExternalBlob)],
        [IDL.Int],
        [],
      ),
    'addReaction' : IDL.Func([IDL.Int, ReactionType], [], []),
    'anyUserHasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBadgeDefinition' : IDL.Func([BadgeDefinition], [], []),
    'daysWithAnyAvailability' : IDL.Func(
        [IDL.Vec(IDL.Int)],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    'decrementDailyLog' : IDL.Func([IDL.Int, IDL.Bool], [], []),
    'deleteAllDayAvailabilities' : IDL.Func([IDL.Int], [], []),
    'deleteBadgeDefinition' : IDL.Func([IDL.Text], [], []),
    'deleteCallerDayAvailability' : IDL.Func([IDL.Int], [], []),
    'deletePost' : IDL.Func([IDL.Int], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'deleteUserDayAvailability' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'editPost' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'getAllAvailabilities' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int, IDL.Text))],
        ['query'],
      ),
    'getAllBadgeDefinitions' : IDL.Func(
        [],
        [IDL.Vec(BadgeDefinition)],
        ['query'],
      ),
    'getAllDayAvailabilityCounts' : IDL.Func(
        [],
        [IDL.Vec(DayAvailabilityCount)],
        ['query'],
      ),
    'getAllLoginTimestamps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'getAllRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile, IDL.Int))],
        ['query'],
      ),
    'getCallerAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(Availability)],
        ['query'],
      ),
    'getCallerAvailableDaysWithLogs' : IDL.Func(
        [],
        [IDL.Vec(DayWithLog)],
        ['query'],
      ),
    'getCallerStats' : IDL.Func([], [IDL.Opt(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayAvailability' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Availability))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getPostWithReplies' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(PostWithReplies)],
        ['query'],
      ),
    'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getReplies' : IDL.Func([IDL.Int], [IDL.Vec(Post)], ['query']),
    'getScoreLeaderboardWithStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T, IDL.Int))],
        ['query'],
      ),
    'getTopPlayersByScore' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T))],
        ['query'],
      ),
    'getUserBadges' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
    'hasAvailability' : IDL.Func([IDL.Int], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordDailyLoss' : IDL.Func([IDL.Int], [], []),
    'recordDailyWin' : IDL.Func([IDL.Int], [], []),
    'recordLoginTime' : IDL.Func([], [], []),
    'removeReaction' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBadgeDefinition' : IDL.Func([BadgeDefinition], [], []),
    'updateCallerStats' : IDL.Func([T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };