/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    customProfilePicture?: ExternalBlob;
}
export interface SeasonSnapshot {
    leaderboard: Array<[Principal, T]>;
    year: bigint;
}
export interface Availability {
    time: string;
    notes?: string;
}
export interface MonthCriteria {
    month: bigint;
    matchesThreshold: bigint;
    year: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BadgeDefinition {
    id: string;
    name: string;
    description: string;
    criteria: BadgeCriteria;
}
export type BadgeCriteria = {
    __kind__: "consecutiveWeeksAvailable";
    consecutiveWeeksAvailable: bigint;
} | {
    __kind__: "firstMatchLogged";
    firstMatchLogged: bigint;
} | {
    __kind__: "totalGamesPlayed";
    totalGamesPlayed: bigint;
} | {
    __kind__: "daysAtNumber1";
    daysAtNumber1: bigint;
} | {
    __kind__: "totalWins";
    totalWins: bigint;
} | {
    __kind__: "winsStreak";
    winsStreak: bigint;
} | {
    __kind__: "totalChatMessages";
    totalChatMessages: bigint;
} | {
    __kind__: "totalGames";
    totalGames: bigint;
} | {
    __kind__: "topLeaderboardPosition";
    topLeaderboardPosition: bigint;
} | {
    __kind__: "winPercentage";
    winPercentage: bigint;
} | {
    __kind__: "monthlyParticipation";
    monthlyParticipation: MonthCriteria;
} | {
    __kind__: "firstImageUploaded";
    firstImageUploaded: bigint;
} | {
    __kind__: "totalDaysAvailable";
    totalDaysAvailable: bigint;
} | {
    __kind__: "totalLikesReceived";
    totalLikesReceived: bigint;
} | {
    __kind__: "bestWinStreak";
    bestWinStreak: bigint;
};
export interface T {
    streak: bigint;
    wins: bigint;
    losses: bigint;
    totalGames: bigint;
    bestStreak: bigint;
}
export interface Post {
    id: bigint;
    content: string;
    edited: boolean;
    author: Principal;
    editTimestamp?: bigint;
    timestamp: bigint;
    image?: ExternalBlob;
    parentId?: bigint;
    likesCount: bigint;
    dislikesCount: bigint;
}
export interface DayWithLog {
    day: bigint;
    wins: bigint;
    losses: bigint;
}
export interface DayAvailabilityCount {
    day: bigint;
    count: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PostWithReplies {
    post: Post;
    replies: Array<PostWithReplies>;
}
export enum ReactionType {
    like = "like",
    dislike = "dislike"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAvailability(day: bigint, time: string, notes: string | null): Promise<void>;
    addPost(content: string, parentId: bigint | null, image: ExternalBlob | null): Promise<bigint>;
    addReaction(postId: bigint, reactionType: ReactionType): Promise<void>;
    anyUserHasAvailability(day: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBadgeToUser(user: Principal, badgeId: string): Promise<void>;
    createBadgeDefinition(definition: BadgeDefinition): Promise<void>;
    daysWithAnyAvailability(days: Array<bigint>): Promise<Array<boolean>>;
    decrementDailyLog(day: bigint, isWin: boolean): Promise<void>;
    deleteAllDayAvailabilities(day: bigint): Promise<void>;
    deleteBadgeDefinition(definitionId: string): Promise<void>;
    deleteCallerDayAvailability(day: bigint): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    deleteUser(userToDelete: Principal): Promise<void>;
    deleteUserDayAvailability(user: Principal, day: bigint): Promise<void>;
    editPost(postId: bigint, newContent: string): Promise<void>;
    finalizeCurrentSeason(year: bigint): Promise<void>;
    getAllAvailabilities(): Promise<Array<[Principal, bigint, string]>>;
    getAllBadgeDefinitions(): Promise<Array<BadgeDefinition>>;
    getAllDayAvailabilityCounts(): Promise<Array<DayAvailabilityCount>>;
    getAllLoginTimestamps(): Promise<Array<[Principal, bigint]>>;
    getAllRegisteredUsers(): Promise<Array<[Principal, UserProfile, bigint]>>;
    getCallerAvailability(day: bigint): Promise<Availability | null>;
    getCallerAvailableDaysWithLogs(): Promise<Array<DayWithLog>>;
    getCallerStats(): Promise<T | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentSeasonLeaderboard(): Promise<Array<[Principal, T]>>;
    getDayAvailability(day: bigint): Promise<Array<[Principal, Availability]>>;
    getLeaderboard(): Promise<Array<[Principal, T]>>;
    getPastSeasonSnapshots(): Promise<Array<SeasonSnapshot>>;
    getPostWithReplies(postId: bigint): Promise<PostWithReplies | null>;
    getPosts(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getReplies(postId: bigint): Promise<Array<Post>>;
    getScoreLeaderboardWithStats(): Promise<Array<[Principal, T, bigint]>>;
    getTopPlayersByScore(limit: bigint): Promise<Array<[Principal, T]>>;
    getTotalPostCount(): Promise<bigint>;
    getUserBadges(user: Principal): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStats(user: Principal): Promise<T | null>;
    hasAvailability(day: bigint): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    recordDailyLoss(day: bigint): Promise<void>;
    recordDailyWin(day: bigint): Promise<void>;
    recordLoginTime(): Promise<void>;
    removeReaction(postId: bigint): Promise<void>;
    revokeBadgeFromUser(user: Principal, badgeId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBadgeDefinition(definition: BadgeDefinition): Promise<void>;
    updateCallerStats(stats: T): Promise<void>;
}
import type { Availability as _Availability, BadgeCriteria as _BadgeCriteria, BadgeDefinition as _BadgeDefinition, ExternalBlob as _ExternalBlob, MonthCriteria as _MonthCriteria, Post as _Post, PostWithReplies as _PostWithReplies, ReactionType as _ReactionType, T as _T, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAvailability(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAvailability(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAvailability(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addPost(arg0: string, arg1: bigint | null, arg2: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPost(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPost(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addReaction(arg0: bigint, arg1: ReactionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, to_candid_ReactionType_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, to_candid_ReactionType_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async anyUserHasAvailability(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.anyUserHasAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.anyUserHasAvailability(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBadgeToUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadgeToUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadgeToUser(arg0, arg1);
            return result;
        }
    }
    async createBadgeDefinition(arg0: BadgeDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBadgeDefinition(to_candid_BadgeDefinition_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBadgeDefinition(to_candid_BadgeDefinition_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async daysWithAnyAvailability(arg0: Array<bigint>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor.daysWithAnyAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daysWithAnyAvailability(arg0);
            return result;
        }
    }
    async decrementDailyLog(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementDailyLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementDailyLog(arg0, arg1);
            return result;
        }
    }
    async deleteAllDayAvailabilities(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllDayAvailabilities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllDayAvailabilities(arg0);
            return result;
        }
    }
    async deleteBadgeDefinition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBadgeDefinition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBadgeDefinition(arg0);
            return result;
        }
    }
    async deleteCallerDayAvailability(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerDayAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerDayAvailability(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteUserDayAvailability(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserDayAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserDayAvailability(arg0, arg1);
            return result;
        }
    }
    async editPost(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1);
            return result;
        }
    }
    async finalizeCurrentSeason(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeCurrentSeason(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeCurrentSeason(arg0);
            return result;
        }
    }
    async getAllAvailabilities(): Promise<Array<[Principal, bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailabilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailabilities();
            return result;
        }
    }
    async getAllBadgeDefinitions(): Promise<Array<BadgeDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBadgeDefinitions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBadgeDefinitions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDayAvailabilityCounts(): Promise<Array<DayAvailabilityCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDayAvailabilityCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDayAvailabilityCounts();
            return result;
        }
    }
    async getAllLoginTimestamps(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoginTimestamps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoginTimestamps();
            return result;
        }
    }
    async getAllRegisteredUsers(): Promise<Array<[Principal, UserProfile, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegisteredUsers();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegisteredUsers();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAvailability(arg0: bigint): Promise<Availability | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAvailability(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAvailability(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAvailableDaysWithLogs(): Promise<Array<DayWithLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAvailableDaysWithLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAvailableDaysWithLogs();
            return result;
        }
    }
    async getCallerStats(): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStats();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStats();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentSeasonLeaderboard(): Promise<Array<[Principal, T]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentSeasonLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentSeasonLeaderboard();
            return result;
        }
    }
    async getDayAvailability(arg0: bigint): Promise<Array<[Principal, Availability]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayAvailability(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayAvailability(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<[Principal, T]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getPastSeasonSnapshots(): Promise<Array<SeasonSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastSeasonSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastSeasonSnapshots();
            return result;
        }
    }
    async getPostWithReplies(arg0: bigint): Promise<PostWithReplies | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostWithReplies(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostWithReplies(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts(arg0, arg1);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts(arg0, arg1);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplies(arg0: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplies(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplies(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScoreLeaderboardWithStats(): Promise<Array<[Principal, T, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreLeaderboardWithStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreLeaderboardWithStats();
            return result;
        }
    }
    async getTopPlayersByScore(arg0: bigint): Promise<Array<[Principal, T]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPlayersByScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPlayersByScore(arg0);
            return result;
        }
    }
    async getTotalPostCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPostCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPostCount();
            return result;
        }
    }
    async getUserBadges(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBadges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBadges(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(arg0: Principal): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAvailability(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAvailability(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordDailyLoss(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailyLoss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailyLoss(arg0);
            return result;
        }
    }
    async recordDailyWin(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailyWin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailyWin(arg0);
            return result;
        }
    }
    async recordLoginTime(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLoginTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLoginTime();
            return result;
        }
    }
    async removeReaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return result;
        }
    }
    async revokeBadgeFromUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeBadgeFromUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeBadgeFromUser(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBadgeDefinition(arg0: BadgeDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBadgeDefinition(to_candid_BadgeDefinition_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBadgeDefinition(to_candid_BadgeDefinition_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCallerStats(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerStats(arg0);
            return result;
        }
    }
}
function from_candid_Availability_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Availability): Availability {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_BadgeCriteria_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeCriteria): BadgeCriteria {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_BadgeDefinition_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeDefinition): BadgeDefinition {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PostWithReplies_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostWithReplies): Promise<PostWithReplies> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Availability]): Availability | null {
    return value.length === 0 ? null : from_candid_Availability_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T]): T | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostWithReplies]): Promise<PostWithReplies | null> {
    return value.length === 0 ? null : await from_candid_PostWithReplies_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    criteria: _BadgeCriteria;
}): {
    id: string;
    name: string;
    description: string;
    criteria: BadgeCriteria;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        criteria: from_candid_BadgeCriteria_n23(_uploadFile, _downloadFile, value.criteria)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    customProfilePicture: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    customProfilePicture?: ExternalBlob;
}> {
    return {
        name: value.name,
        customProfilePicture: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.customProfilePicture))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    time: string;
    notes: [] | [string];
}): {
    time: string;
    notes?: string;
} {
    return {
        time: value.time,
        notes: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.notes))
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    post: _Post;
    replies: Array<_PostWithReplies>;
}): Promise<{
    post: Post;
    replies: Array<PostWithReplies>;
}> {
    return {
        post: await from_candid_Post_n44(_uploadFile, _downloadFile, value.post),
        replies: await from_candid_vec_n47(_uploadFile, _downloadFile, value.replies)
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    edited: boolean;
    author: Principal;
    editTimestamp: [] | [bigint];
    timestamp: bigint;
    image: [] | [_ExternalBlob];
    parentId: [] | [bigint];
    likesCount: bigint;
    dislikesCount: bigint;
}): Promise<{
    id: bigint;
    content: string;
    edited: boolean;
    author: Principal;
    editTimestamp?: bigint;
    timestamp: bigint;
    image?: ExternalBlob;
    parentId?: bigint;
    likesCount: bigint;
    dislikesCount: bigint;
}> {
    return {
        id: value.id,
        content: value.content,
        edited: value.edited,
        author: value.author,
        editTimestamp: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.editTimestamp)),
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.image)),
        parentId: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.parentId)),
        likesCount: value.likesCount,
        dislikesCount: value.dislikesCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile, bigint]): Promise<[Principal, UserProfile, bigint]> {
    return [
        value[0],
        await from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[1]),
        value[2]
    ];
}
function from_candid_tuple_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _Availability]): [Principal, Availability] {
    return [
        value[0],
        from_candid_Availability_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    consecutiveWeeksAvailable: bigint;
} | {
    firstMatchLogged: bigint;
} | {
    totalGamesPlayed: bigint;
} | {
    daysAtNumber1: bigint;
} | {
    totalWins: bigint;
} | {
    winsStreak: bigint;
} | {
    totalChatMessages: bigint;
} | {
    totalGames: bigint;
} | {
    topLeaderboardPosition: bigint;
} | {
    winPercentage: bigint;
} | {
    monthlyParticipation: _MonthCriteria;
} | {
    firstImageUploaded: bigint;
} | {
    totalDaysAvailable: bigint;
} | {
    totalLikesReceived: bigint;
} | {
    bestWinStreak: bigint;
}): {
    __kind__: "consecutiveWeeksAvailable";
    consecutiveWeeksAvailable: bigint;
} | {
    __kind__: "firstMatchLogged";
    firstMatchLogged: bigint;
} | {
    __kind__: "totalGamesPlayed";
    totalGamesPlayed: bigint;
} | {
    __kind__: "daysAtNumber1";
    daysAtNumber1: bigint;
} | {
    __kind__: "totalWins";
    totalWins: bigint;
} | {
    __kind__: "winsStreak";
    winsStreak: bigint;
} | {
    __kind__: "totalChatMessages";
    totalChatMessages: bigint;
} | {
    __kind__: "totalGames";
    totalGames: bigint;
} | {
    __kind__: "topLeaderboardPosition";
    topLeaderboardPosition: bigint;
} | {
    __kind__: "winPercentage";
    winPercentage: bigint;
} | {
    __kind__: "monthlyParticipation";
    monthlyParticipation: MonthCriteria;
} | {
    __kind__: "firstImageUploaded";
    firstImageUploaded: bigint;
} | {
    __kind__: "totalDaysAvailable";
    totalDaysAvailable: bigint;
} | {
    __kind__: "totalLikesReceived";
    totalLikesReceived: bigint;
} | {
    __kind__: "bestWinStreak";
    bestWinStreak: bigint;
} {
    return "consecutiveWeeksAvailable" in value ? {
        __kind__: "consecutiveWeeksAvailable",
        consecutiveWeeksAvailable: value.consecutiveWeeksAvailable
    } : "firstMatchLogged" in value ? {
        __kind__: "firstMatchLogged",
        firstMatchLogged: value.firstMatchLogged
    } : "totalGamesPlayed" in value ? {
        __kind__: "totalGamesPlayed",
        totalGamesPlayed: value.totalGamesPlayed
    } : "daysAtNumber1" in value ? {
        __kind__: "daysAtNumber1",
        daysAtNumber1: value.daysAtNumber1
    } : "totalWins" in value ? {
        __kind__: "totalWins",
        totalWins: value.totalWins
    } : "winsStreak" in value ? {
        __kind__: "winsStreak",
        winsStreak: value.winsStreak
    } : "totalChatMessages" in value ? {
        __kind__: "totalChatMessages",
        totalChatMessages: value.totalChatMessages
    } : "totalGames" in value ? {
        __kind__: "totalGames",
        totalGames: value.totalGames
    } : "topLeaderboardPosition" in value ? {
        __kind__: "topLeaderboardPosition",
        topLeaderboardPosition: value.topLeaderboardPosition
    } : "winPercentage" in value ? {
        __kind__: "winPercentage",
        winPercentage: value.winPercentage
    } : "monthlyParticipation" in value ? {
        __kind__: "monthlyParticipation",
        monthlyParticipation: value.monthlyParticipation
    } : "firstImageUploaded" in value ? {
        __kind__: "firstImageUploaded",
        firstImageUploaded: value.firstImageUploaded
    } : "totalDaysAvailable" in value ? {
        __kind__: "totalDaysAvailable",
        totalDaysAvailable: value.totalDaysAvailable
    } : "totalLikesReceived" in value ? {
        __kind__: "totalLikesReceived",
        totalLikesReceived: value.totalLikesReceived
    } : "bestWinStreak" in value ? {
        __kind__: "bestWinStreak",
        bestWinStreak: value.bestWinStreak
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BadgeDefinition>): Array<BadgeDefinition> {
    return value.map((x)=>from_candid_BadgeDefinition_n21(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile, bigint]>): Promise<Array<[Principal, UserProfile, bigint]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _Availability]>): Array<[Principal, Availability]> {
    return value.map((x)=>from_candid_tuple_n40(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostWithReplies>): Promise<Array<PostWithReplies>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostWithReplies_n42(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n44(_uploadFile, _downloadFile, x)));
}
function to_candid_BadgeCriteria_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BadgeCriteria): _BadgeCriteria {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_BadgeDefinition_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BadgeDefinition): _BadgeDefinition {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ReactionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReactionType): _ReactionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    criteria: BadgeCriteria;
}): {
    id: string;
    name: string;
    description: string;
    criteria: _BadgeCriteria;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        criteria: to_candid_BadgeCriteria_n18(_uploadFile, _downloadFile, value.criteria)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    customProfilePicture?: ExternalBlob;
}): Promise<{
    name: string;
    customProfilePicture: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        customProfilePicture: value.customProfilePicture ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.customProfilePicture)) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReactionType): {
    like: null;
} | {
    dislike: null;
} {
    return value == ReactionType.like ? {
        like: null
    } : value == ReactionType.dislike ? {
        dislike: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "consecutiveWeeksAvailable";
    consecutiveWeeksAvailable: bigint;
} | {
    __kind__: "firstMatchLogged";
    firstMatchLogged: bigint;
} | {
    __kind__: "totalGamesPlayed";
    totalGamesPlayed: bigint;
} | {
    __kind__: "daysAtNumber1";
    daysAtNumber1: bigint;
} | {
    __kind__: "totalWins";
    totalWins: bigint;
} | {
    __kind__: "winsStreak";
    winsStreak: bigint;
} | {
    __kind__: "totalChatMessages";
    totalChatMessages: bigint;
} | {
    __kind__: "totalGames";
    totalGames: bigint;
} | {
    __kind__: "topLeaderboardPosition";
    topLeaderboardPosition: bigint;
} | {
    __kind__: "winPercentage";
    winPercentage: bigint;
} | {
    __kind__: "monthlyParticipation";
    monthlyParticipation: MonthCriteria;
} | {
    __kind__: "firstImageUploaded";
    firstImageUploaded: bigint;
} | {
    __kind__: "totalDaysAvailable";
    totalDaysAvailable: bigint;
} | {
    __kind__: "totalLikesReceived";
    totalLikesReceived: bigint;
} | {
    __kind__: "bestWinStreak";
    bestWinStreak: bigint;
}): {
    consecutiveWeeksAvailable: bigint;
} | {
    firstMatchLogged: bigint;
} | {
    totalGamesPlayed: bigint;
} | {
    daysAtNumber1: bigint;
} | {
    totalWins: bigint;
} | {
    winsStreak: bigint;
} | {
    totalChatMessages: bigint;
} | {
    totalGames: bigint;
} | {
    topLeaderboardPosition: bigint;
} | {
    winPercentage: bigint;
} | {
    monthlyParticipation: _MonthCriteria;
} | {
    firstImageUploaded: bigint;
} | {
    totalDaysAvailable: bigint;
} | {
    totalLikesReceived: bigint;
} | {
    bestWinStreak: bigint;
} {
    return value.__kind__ === "consecutiveWeeksAvailable" ? {
        consecutiveWeeksAvailable: value.consecutiveWeeksAvailable
    } : value.__kind__ === "firstMatchLogged" ? {
        firstMatchLogged: value.firstMatchLogged
    } : value.__kind__ === "totalGamesPlayed" ? {
        totalGamesPlayed: value.totalGamesPlayed
    } : value.__kind__ === "daysAtNumber1" ? {
        daysAtNumber1: value.daysAtNumber1
    } : value.__kind__ === "totalWins" ? {
        totalWins: value.totalWins
    } : value.__kind__ === "winsStreak" ? {
        winsStreak: value.winsStreak
    } : value.__kind__ === "totalChatMessages" ? {
        totalChatMessages: value.totalChatMessages
    } : value.__kind__ === "totalGames" ? {
        totalGames: value.totalGames
    } : value.__kind__ === "topLeaderboardPosition" ? {
        topLeaderboardPosition: value.topLeaderboardPosition
    } : value.__kind__ === "winPercentage" ? {
        winPercentage: value.winPercentage
    } : value.__kind__ === "monthlyParticipation" ? {
        monthlyParticipation: value.monthlyParticipation
    } : value.__kind__ === "firstImageUploaded" ? {
        firstImageUploaded: value.firstImageUploaded
    } : value.__kind__ === "totalDaysAvailable" ? {
        totalDaysAvailable: value.totalDaysAvailable
    } : value.__kind__ === "totalLikesReceived" ? {
        totalLikesReceived: value.totalLikesReceived
    } : value.__kind__ === "bestWinStreak" ? {
        bestWinStreak: value.bestWinStreak
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
